### ISSUE TITLE
Footnote

### ISSUE THREAD

**Issue by mudfly** [vaarn/vaarn.github.io#11]
In referee-rules.md there is a footnote under the Rations section. I am not sure how best to use this for web, so I am leaving this bug here to remind me. Perhaps Leo can guide how this information is relayed.

**Comment by GraculusDroog** [comment]
As it's intended as a throwaway joke I don't know that it's necessary for understanding the rules. I think if we want to include footnotes they make most sense in parenthesis.

**Comment by mudfly** [comment]
When I left this issue I was unsure if I was going to come across additional footnotes, so this issue was a reminder for myself. I agree that using parentheses for the single footnote is the best solution.

**Comment by mudfly** [comment]
I've dropped the footnote from the SRD.
