### ISSUE TITLE
remove duplicate tables from VoV #1

### ISSUE THREAD

**Issue by mudfly** [vaarn/vaarn.github.io#14]
The tables that are under the **Content Generators** header come from VoV #1. Some of these tables were revised and added to the **Creating Regions** section of VoV #3. The duplicate tables under **Content Generators** need to be removed.

**Comment by mudfly** [comment]
I've removed Oasis and Arcology Dome from **Content Generators**, the flavor text from Arcology Dome I moved to the Arcology section under **Creating Regions**.

Should I also remove Ruins of Vaarn from Content Generators?

**Comment by mudfly** [comment]
@GraculusDroog

**Comment by GraculusDroog** [comment]
Yeah the Ruins table was improved on in issue 3 so I think the version in content generators isn’t needed 

Leo

**Comment by mudfly** [comment]
Leo took care of the Ruins table, as well as a few others. Thanks!
