### ISSUE TITLE
Font Color CSS

### ISSUE THREAD

**Issue by mudfly** [vaarn/vaarn.github.io#16]
Update the vov.css stylesheet to override the green color of the text from the default Docsify theme.

@GraculusDroog do you have any preference on the hyperlink highlighting color?  I was thinking the blue-gray (#92BEC7) from the background of VoV #1's itch page.

**Comment by GraculusDroog** [comment]
Yeah I think using the blue from the first issue cover would work well. 

Leo

**Comment by mudfly** [comment]
I've change the color, what do you think?

**Comment by GraculusDroog** [comment]
It looks good! It’s not too bright which I like. 

Leo

**Comment by mudfly** [comment]
great, closing issue.
