### ISSUE TITLE
Add issue 1 images

### ISSUE THREAD

**Issue by mudfly** [vaarn/vaarn.github.io#6]
Add the images for issue 1 to the SRD.

**Comment by mudfly** [comment]
I am now leaning towards not adding the images from the zines to the SRD, except in minor areas such as the weather hex flower that is a game aid. I feel like it makes the resource easier to use at the table, while also pushing players to get a physical or digital copy of the zines for the graphics, color, and layout to help set the tone. Do you have any thoughts on this @GraculusDroog?

**Comment by GraculusDroog** [comment]
I would be inclined to agree, I think except in the cases where as you say the image is necessary to understand the information i would keep it as text only. 

Leo

**Comment by mudfly** [comment]
Will not import images into SRD, closing issue.
